cd bindings
rmdir /s /q build
mkdir build
cd build

cmake -G "Ninja" ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DBUILD_SHARED_LIBS:BOOL=ON ^
    -DPython3_EXECUTABLE:PATH=%PYTHON% ^
    -DFRAMEWORK_DETECT_ACTIVE_PYTHON_SITEPACKAGES:BOOL=ON ^
    ..
if errorlevel 1 exit 1

:: Build.
cmake --build . --config Release
if errorlevel 1 exit 1

:: Install.
cmake --build . --config Release --target install
if errorlevel 1 exit 1

:: The BindingsSystem target is a C++ INTERFACE (header-only) library defined in the
:: bindings, but it needs to be available as a BipedalLocomotion:: CMake target for
:: downstream C++ consumers. Since the C++ build (bld_cxx.bat) sets
:: FRAMEWORK_COMPILE_PYTHON_BINDINGS=OFF, BindingsSystem is not exported there.
:: We manually create the target file and include it from the existing config.
set BLF_CMAKE_DIR=%LIBRARY_PREFIX%\CMake

(
echo # Generated by the conda recipe to export targets built by the Python bindings package.
echo # PACKAGE_PREFIX_DIR is set by BipedalLocomotionFrameworkConfig.cmake before including this file.
echo if^(NOT TARGET BipedalLocomotion::BindingsSystem^)
echo   add_library^(BipedalLocomotion::BindingsSystem INTERFACE IMPORTED^)
echo   set_target_properties^(BipedalLocomotion::BindingsSystem PROPERTIES
echo     INTERFACE_COMPILE_FEATURES "cxx_std_17"
echo     INTERFACE_INCLUDE_DIRECTORIES "${PACKAGE_PREFIX_DIR}/include"
echo     INTERFACE_LINK_LIBRARIES "BipedalLocomotion::System"
echo   ^)
echo endif^(^)
) > "%BLF_CMAKE_DIR%\BipedalLocomotionFrameworkBindingsTargets.cmake"
if errorlevel 1 exit 1

(
echo.
echo # Include bindings targets if available ^(installed by the Python bindings package^)
echo include^("${CMAKE_CURRENT_LIST_DIR}/BipedalLocomotionFrameworkBindingsTargets.cmake" OPTIONAL^)
) >> "%BLF_CMAKE_DIR%\BipedalLocomotionFrameworkConfig.cmake"
if errorlevel 1 exit 1

:: Tests are not installed, so we run them during the build
:: We run them directly via pytest so we detect if we are not compiling some required components
cd ..
pytest -v -k "not (test_load_from_file or test_fixed_foot_detector)"
if errorlevel 1 exit 1
